env:
  global:
    - CC_TEST_REPORTER_ID=CC_TEST_REPORTER_ID
language: node_js
node_js:
  - 8
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate < test/coverage/**/lcov.info
